### ISSUE TITLE
requirement language around CL and IL

### ISSUE THREAD

**Issue by thomas-fossati** [yaronf/I-D#440] opened 2022-07-13 05:55 UTC
```
** Section 4.4
        When a sender is approaching CL, the implementation SHOULD initiate a
        new handshake (or in TLS 1.3, a Key Update) to rotate the session
        key.

        When a receiver has reached IL, the implementation SHOULD close the
        connection.

Should these normative SHOULDs be MUSTs?  What is the circumstance where it
would be prudent or necessary sender to use the existing key material after the
CL has been exceeded?  Same issue on the IL limit.
```

cc @danilyw

**Comment by thomas-fossati** [comment] 2022-07-13 10:14
I think the rationale we utilised was: use 1.3 as the reference point for 1.2:

| proto | original req level | BCP195 req level |
| -- | -- | -- |
| [TLS 1.3 (§5.5)](https://datatracker.ietf.org/doc/html/rfc8446#section-5.5) | SHOULD | SHOULD |
| [DTLS 1.3 (§4.5.3)](https://datatracker.ietf.org/doc/html/rfc9147#section-4.5.3) | SHOULD  | SHOULD |
| TLS 1.2 | none | SHOULD |

It's true that [QUIC is more stringent](https://datatracker.ietf.org/doc/html/rfc9001#section-6.6), but it also uses a different record layer than (D)TLS so we didn't take it into consideration.

Personally, I'd wait for 8446bis to see if they move to a MUST.

**Comment by stpeter** [comment] 2022-07-18 19:54
This seems to be a duplicate of https://github.com/yaronf/I-D/issues/444 so I'm closing this one.

**Closed by stpeter** 2022-07-18 19:54 UTC
Labels: IESG review, BCP195, comment
